version: '3.1'
# service
services:
    node:
        image: node:14
        tty: true
        restart: always
        volumes: 
            - ./sources:/app:cached
        working_dir: /app
        ports:
            - 3000:3000
            - 1337:1337
        environment: 
            HOST: 0.0.0.0
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: checkin@1325
            POSTGRES_USER: check1Nvi3tNam
            POSTGRES_DB: checkinvietnam
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./db/pgdata:/var/lib/postgresql/data:cached